language: cpp
compiler: gcc
before_install:
  - gcc --version
  - sudo apt-get update -qq
  - sudo apt-get install arduino arduino-core arduino-mk python-pip
  - pip install ino
  - ino build --help
install:
  - ino build -m mega2560