language: cpp
compiler: gcc
before_install:
  - gcc --version
  - sudo apt-get update -qq
  - sudo apt-get install -qq arduino arduino-core arduino-mk python-setuptools python-pip
  - sudo pip install ino
  - ino build --help
install:
  - ino build -m mega2560