language: cpp
compiler: avr-gcc
python:
  - "2.7"
before_install:
  - gcc --version
  - sudo apt-get update -qq
  - sudo apt-get install arduino arduino-core arduino-mk python-setuptools python-pip -qq
  - sudo pip install ino
install:
  - ino build -m mega
  - true