env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "TBH1lv8uRb/QkZl1FHCQbx5WE/xPdbSvqGaVXB6WAplklfUGjamgCy9MkpUhrj6pB+AtFjGtksCS87uv8Q4sYQaZbn6pmGX1EVy4kTejfpJf3uvL7qtjb7FQkvIjnQMuoPKYR3Rh5rDx/rI7L86sUm2eehbCtcoHpIHGwaI9w/4="

language: cpp
compiler: gcc
python:
  - "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq arduino arduino-core arduino-mk python-setuptools python-pip clang
  - sudo pip install ino
install: ino build -m mega
#before_script: true
script: make -f .build/mega/Makefile
#Clang scanner
after_script: scan-build -k -o ./ make -f .build/mega/Makefile

addons:
  coverity_scan:
    project:
      name: "ehooo/Weather_Station"
      description: "Wheater station"
    build_command_prepend:
    build_command: make
    branch_pattern: coverity_scan